pymongo_auth_aws/__init__.py,sha256=vVXmWNpo2AelXeZjPr10gU0FKzLB_w3iIS7RP4xki2A,751
pymongo_auth_aws/auth.py,sha256=fDHX-zotCrFXpzHCWx56dfplHApsZgoG_9bhUFicCEo,8361
pymongo_auth_aws/errors.py,sha256=ilEemepO2UD-cW5C7ZjiQWhZCmidDHlSheoWB1_2rro,725
pymongo_auth_aws/version.py,sha256=6X6jM4yXeS7wKibLmwAsf5IMqijsPHQNS38voXdn1YY,604
pymongo_auth_aws-1.2.0.dist-info/METADATA,sha256=Cur8KoemHGvo-l0qkiqTekkiJVIvoKR-I6ljefGqNxk,17678
pymongo_auth_aws-1.2.0.dist-info/WHEEL,sha256=1yFddiXMmvYK7QYTqtRNtX66WJ0Mz8PYEiEUoOUUxRY,87
pymongo_auth_aws-1.2.0.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
pymongo_auth_aws-1.2.0.dist-info/RECORD,,
